<?php
/** @var \BSD\Theme\Block\Home\Sections $block */
$heroDesktop = $block->getHeroBannerUrl();
$heroMobile = $block->getHeroMobileBannerUrl();
?>
<link rel="preload"
      as="image"
      type="image/webp"
      href="<?= $block->escapeUrl($heroMobile) ?>"
      media="(max-width: 1023px)"
      fetchpriority="high"/>
<link rel="preload"
      as="image"
      type="image/webp"
      href="<?= $block->escapeUrl($heroDesktop) ?>"
      media="(min-width: 1024px)"
      fetchpriority="high"/>
