<?php

declare(strict_types=1);

use BSD\Storefront\ViewModel\HomePromotionalPreload;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HomePromotionalPreload $preloadViewModel */
$preloadViewModel = $viewModels->require(HomePromotionalPreload::class);

foreach ($preloadViewModel->getPreloadImageUrls() as $imageUrl): ?>
<link rel="preload" as="image" href="<?= $escaper->escapeUrl($imageUrl) ?>">
<?php endforeach; ?>
