<?php
/** @var \Magento\LayeredNavigation\Block\Navigation $block */
?>
<?php if ($block->canShowBlock()): ?>
<div class="bd-filters block filter">
    <h2 class="bd-filters__title"><?= $block->escapeHtml(__('Filters')) ?></h2>
    <div class="block-content filter-content">
        <?= $block->getChildHtml('state') ?>
        <?php if ($block->getLayer()->getState()->getFilters()): ?>
            <div class="block-actions filter-actions">
                <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                    <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                </a>
            </div>
        <?php endif; ?>
        <?php $wrapOptions = false; ?>
        <?php foreach ($block->getFilters() as $filter): ?>
            <?php if (!$wrapOptions): ?>
                <dl class="filter-options" id="narrow-by-list">
                <?php $wrapOptions = true; endif; ?>
            <?php if ($filter->getItemsCount()): ?>
                <dt class="filter-options-title"><?= $block->escapeHtml($filter->getName()) ?></dt>
                <dd class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if ($wrapOptions): ?></dl><?php endif; ?>
    </div>
</div>
<?php endif; ?>
