<?php
/**
 * BulkDevices footer copyright
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Footer;

/** @var Footer $block */
/** @var Escaper $escaper */
?>
<p class="site-footer__copyright">
    <?= $escaper->escapeHtml(
        __('© Cube Devices Corp working as Bulk Devices , trademarks and tradenames are acknowledged. Bulk Devices hold no affiliation to any of the Trademark owners.')
    ) ?>
</p>
