<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$defaultOpenFilters = ['cat', 'price'];
?>
<?php if ($block->canShowBlock()): ?>
    <div
        x-data="initLayeredNavigation()"
        x-init="checkIsMobileResolution()"
        @resize.window.debounce="checkIsMobileResolution()"
        @visibilitychange.window.debounce="checkIsMobileResolution()"
        class="bb-plp-filters block"
        role="region"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Product filters')) ?>"
    >
        <h2
            id="filters-heading"
            class="bb-plp-filters__heading block-title"
        >
            <button
                type="button"
                @click="blockOpen = !blockOpen"
                class="bb-plp-filters__heading-btn block-title flex items-center justify-between w-full text-start"
                aria-controls="filters-content"
                :aria-expanded="blockOpen"
                :aria-disabled="!isMobile"
                :disabled="!isMobile ? '' : null"
            >
                <span class="text-md md:text-3xl font-medium uppercase">
                    <?= $escaper->escapeHtml(__('Filters')) ?>
                </span>
                <span
                    class="py-1 px-1 bg-white rounded border border-gray-300 md:hidden"
                    x-ref="LayeredNavigationMobileToggleIcon"
                >
                    <?= $heroicons->chevronDownHtml(
                        'transition-transform transform duration-300 ease-in-out',
                        24,
                        24,
                        [
                            ":class" => "{ 'rotate-180': blockOpen }",
                            "aria-hidden" => "true",
                            "focusable" => "false"
                        ]
                    ); ?>
                </span>
            </button>
        </h2>
        <div
            id="filters-content"
            class="bb-plp-filters__content block-content filter-content hidden md:block"
            :class="{ 'hidden': !blockOpen }"
        >
            <?= $block->getChildHtml('state') ?>
            <a
                href="#product-list"
                class="sr-only focus:not-sr-only bg-blue-600 text-white px-12 py-4 text-center block rounded-sm"
            >
                <?= $escaper->escapeHtml(__('Skip to product list')) ?>
            </a>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php $isOpenByDefault = in_array($filter->getRequestVar(), $defaultOpenFilters, true); ?>
                    <div
                        x-data="{
                            open: <?= $isOpenByDefault ? 'true' : 'false' ?>,
                            id: $id('filter-option')
                        }"
                        x-defer="intersect"
                        class="bb-plp-filters__group filter-option card"
                    >
                        <h3 :id="`${id}-title`">
                            <button
                                type="button"
                                @click="open = !open"
                                class="bb-plp-filters__group-title filter-options-title flex justify-between items-center cursor-pointer text-start w-full"
                                :class="{ 'border-b pb-4': open }"
                                :aria-controls="`${id}-content`"
                                :aria-expanded="open"
                            >
                                <span class="title text-md md:text-lg font-semibold">
                                    <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                    <span class="sr-only"> <?= $escaper->escapeHtml(__('filter')) ?></span>
                                </span>
                                    <span class="py-1 px-1 rounded border border-gray-300">
                                    <?= $heroicons->chevronDownHtml(
                                        'transition-transform transform duration-300 ease-in-out',
                                        24,
                                        24,
                                        [
                                            ":class" => "{ 'rotate-180': open }",
                                            "aria-hidden" => "true",
                                            "focusable" => "false"
                                        ]
                                    ); ?>
                                </span>
                            </button>
                        </h3>
                        <template x-if="open">
                            <div
                                :id="`${id}-content`"
                                class="bb-plp-filters__group-content filter-options-content"
                            >
                                <?= /* @noEscape */ $block->getChildBlock('renderer')->setFilterTitle($filter->getName())->render($filter); ?>
                            </div>
                        </template>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution() {
                    const mobileElement = this.$refs.LayeredNavigationMobileToggleIcon;
                    this.isMobile = mobileElement
                        ? getComputedStyle(mobileElement).display !== "none"
                        : window.matchMedia('(max-width: 767px)').matches;
                }
            }
        }
    </script>
<?php endif; ?>
