<?php $_product = $block->getProduct();
$image = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'product_base_image')->constrainOnly(true)->keepAspectRatio(true)->keepTransparency(true)->keepFrame(false)->resize(150, 150)->getUrl();

if ($_product->getFinalPrice() == 0): ?>
    <div class="pdp-getquote">
        <button class="action primary tocart" href="#" id="click-me">Call For Price</button>
    </div>

    <div id="callforprice" class="call-for-price-modal-popup-product" style="display:none;">

        <div class="row">
            <div class="col-md-6">
                <img src="<?php echo $image ?>" style="margin-bottom: 0;"/>
                <h4><?php echo $_product->getSku(); ?></h4>
            </div>
            <div class="col-md-6">

                <form name="call_for_price" method="post" id="call_for_price" class="form"
                      action="<?php /* @escapeNotVerified */
                      echo $block->getFormAction(); ?>"
                      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                      data-mage-init='{"validation":{}}'>
                    <p class="responce_message_call_price" style="padding: 5px 10px;text-align: center;"></p>


                    <fieldset class="fieldset">
                        <legend class="legend">
                            <span><?= $block->escapeHtmlAttr(__('Request For Free Quotation')) ?></span></legend>
                        <fieldset class="fieldset row">
                            <div class="fields col-md-12">
                                <div class="field name required">
                                    <div class="control">
                                        <input placeholder="<?= $block->escapeHtmlAttr(__('Name')) ?>" name="name"
                                               id="name" title="Name" value="" class="input-text" type="text"
                                               data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                                    </div>
                                </div>

                                <div class="field name required">
                                    <div class="control">
                                        <input placeholder="<?= $block->escapeHtmlAttr(__('Telephone')) ?>"
                                               name="phone" id="phone" title="Telephone" value=""
                                               class="input-text"
                                               type="text" data-validate="{required:true}">
                                    </div>
                                </div>

                                <div class="field name required">
                                    <div class="control">
                                        <input placeholder="<?= $block->escapeHtmlAttr(__('Email')) ?>" name="email"
                                               id="email" title="Email" value="" class="input-text" type="text"
                                               data-validate="{required:true, 'validate-email':true}">
                                    </div>
                                </div>

                               <?php /* <div class="field name required">
                                    <div class="control">
                                        <input placeholder="<?= $block->escapeHtmlAttr(__('Price')) ?>" name="price"
                                               id="price" title="price" value="" class="input-text"
                                               type="text" data-validate="{required:true}">
                                    </div>
                                </div>

                                <div class="field name required">
                                    <div class="control">
                                        <input placeholder="<?= $block->escapeHtmlAttr(__('Quantity')) ?>"
                                               name="quantity" id="quantity" title="quantity" value=""
                                               class="input-text"
                                               type="text" data-validate="{required:true}">
                                    </div>
                                </div>*/ ?>
                            </div>
                        </fieldset>
                    </fieldset>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <input type="hidden" name="request_type" id="request_type" value="Call For Price"/>
                            <input name="sku" id="sku" title="sku" value="<?php echo $_product->getSku(); ?>" class="input-text"
                                   type="hidden" data-validate="{required:true}">
                            <button type="submit" class="action submit_call_for_price primary" title="Save">
                                <span><?= $block->escapeHtmlAttr(__('Send')) ?></span></button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>

    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function ($, modal) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    buttons: [],
                    modalClass: "call-for-price-modal-pdp-popup"
                };

                // var popup = modal(options, $('#popup-modal'));
                // $("#click-me").on('click', function () {
                //     $("#popup-modal").modal("openModal");
                // });
                $(document).on('click', '#click-me', function (event) {
                    event.preventDefault();
                    var popup = modal(options, $('#callforprice'));
                    $('#callforprice').modal(options).modal('openModal');
                });

            }
        );
    </script>

    <script type="text/javascript">
        require([
            "jquery",
            "jquery/ui"
        ], function ($v) {
//<![CDATA[
            $v = jQuery.noConflict();
            $v(document).ready(function () {
                var dataForm = $v('#call_for_price');
                var base_url = window.location.origin;
                var AjaxUrl = base_url + '/getaquote/Index/formpost/';
                //var AjaxUrl = '<?php //echo 'https://www.gracileit.com/getaquote/Index/formpost'?>//';
                console.log('jquery loaded from emq.js');
                $v(".submit_call_for_price").on('click', function (e) {
                    var param = dataForm.serialize();
                    console.log(param);
                    $v.ajax({
                        showLoader: true,
                        url: AjaxUrl,
                        data: param,
                        type: "POST"
                    }).done(function (data) {
                        $v('.responce_message_call_price').html(data);
                        $v('.responce_message_call_price').css('color', 'red');
                        document.getElementById("call_for_price").reset();
                        setTimeout(function(){
                            $v('.responce_message_call_price').empty();
                            $v("#callforprice").modal("closeModal");
                        }, 3000);


                    });
                    return false;
                });
                $v('.product-info-main').find('.pdp-getquote').closest('.product-info-price').addClass('getquote-active');
            });
//]]>
        });
    </script>
    <style type="text/css">
        .modal-popup .modal-inner-wrap {
            width: 40%;
        }
    </style>


<?php endif; ?>


