<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>
<script>
    window.renderBadge = function() {
        var ratingBadgeContainer = document.createElement("div");
        document.body.appendChild(ratingBadgeContainer);
        window.gapi.load('ratingbadge', function() {
            window.gapi.ratingbadge.render(
                ratingBadgeContainer, {
                    "merchant_id": "<?php echo $block->escapeHtml($block->getBadgeMerchantId()); ?>",
                    "position": "BOTTOM_LEFT"
                });

        });
        // console.log(ratingBadgeContainer);
    }
</script>
<script>
    window.___gcfg = {
        lang: 'en-US'
    };
</script>
