<!-- BEGIN GCR Opt-in Module Code -->
<script src="https://apis.google.com/js/platform.js?onload=renderOptIn" async defer></script>
<script>
    window.renderOptIn = function() {
        window.gapi.load('surveyoptin', function() {
            window.gapi.surveyoptin.render({
                // REQUIRED
                "merchant_id": "<?php echo $block->escapeHtml($block->getMerchantId()); ?>",
                "order_id": "<?php echo $block->escapeHtml($block->getOrderId()); ?>",
                "email": "<?php echo $block->escapeHtml($block->getCustomerEmail()); ?>",
                "delivery_country": "<?php echo $block->escapeHtml($block->getDeliveryCountryCode()); ?>",
                "estimated_delivery_date": "<?php echo $block->escapeHtml($block->getOrderDate()); ?>",
                "opt_in_style": "CENTER_DIALOG"
            });
        });
    }
</script>
<!-- END GCR Opt-in Module Code -->
<!-- BEGIN GCR Language Code -->

<script>

window.___gcfg = {

lang: 'en-US'

};

</script>

<!-- END GCR Language Code -->
