<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<footer class="site-footer">
    <?= $block->getChildHtml('footer-middle') ?>
    <div class="site-footer__bottom">
        <div class="container site-footer__bottom-inner">
            <?= $block->getChildHtml('copyright') ?>
        </div>
    </div>
</footer>
