<?php
/**
 * @var \Pnp\ImportGadget\Block\Adminhtml\Index\Index $block
 */
?>


<div class="admin__scope-old">
    <div class="ui-tabs-panel ui-widget-content ui-corner-bottom">
        <div class="entry-edit form-inline">
            <form action="<?php echo $block->getUrl('importgadget/index/upload') ?>" method="post" enctype="multipart/form-data">
                <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>">
                <fieldset class="fieldset admin__fieldset">

                    <div class="admin__field field">
                        <label class="label admin__field-label" for="page_title"><span>Import Images</span></label>
                        <div class="admin__field-control control">
                            <input type="file" name="import_images[]" multiple="multiple" accept="image/png, image/gif, image/jpeg"/>
                        </div>
                    </div>

                    <div class="admin__field field field-image">
                        <label class="label admin__field-label" for="page_image"><span>Directory Name</span></label>
                        <div class="admin__field-control control">
                            <input type="text" name="directory_name"/>
                        </div>
                    </div>

                    <div class="page-actions">
                        <div class="page-actions-buttons">
                            <button id="upload" title="Upload" type="submit" class="action-default save primary ui-button ui-corner-all ui-widget">
                                <span>Upload</span>
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>


<div class="admin__data-grid-wrap admin__data-grid-wrap-static">
    <table class="data-grid">
        <thead>
        <tr>
            <th class="data-grid-th">Directory</th>
        </tr>
        </thead>
        <?php foreach ($block->getAllFiles() as $dir) : ?>
            <tr>
                <td><?= $dir ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>