<?php
declare(strict_types=1);
namespace BSD\ProductAttributes\Model\Config;
class SharedAttributeOptionAdditions
{
    public static function getAdditions(): array
    {
        return [
            'capacity' => [
                '2000TB',
                '146.GB',
                '12000TB',
                '4000TB',
                '365GB',
                '785GB',
                '1.28TB',
                '512GB',
                '100GB',
                '64GB',
                '480GB',
                '3.84TB',
                '80GB',
                '192GB',
                '1.60TB',
                '90GB',
                '340GB',
                '149GB',
                '1.92TB',
                '6GB',
                '72GB',
                '1.9TB',
                '175GB',
                '700GB',
                '1600GB',
                '3840GB',
                '1920GB',
                '3200GB',
                '930GB',
                '3.2TB',
                '3.8TB',
                '275GB',
                '525GB',
                '1.0TB',
                '2.1GB',
                '768GB',
                '73GB',
                '775GB',
                '7.68TB',
                '15.3TB',
                '5.76TB',
                '23.04TB',
                '280GB',
                '375GB',
                '118GB',
                '1.20TB',
                '1.024TB',
                '177GB',
                '387GB',
                '920GB',
                '512MB',
                '15.36TB',
                '2.048TB',
                '27.6TB',
                '6.9TB',
                '13.2TB',
                '90TB',
                '20.7TB',
                '19.8TB',
                '34TB',
                '66TB',
                '120TB',
                '16.2TB',
                '60TB',
                '62TB',
                '26.4TB',
                '64TB',
                '6.6TB',
                '128TB',
                '25.2TB',
                '136TB',
                '33TB',
                '11TB',
                '13.8TB',
                '102TB',
                '354TB',
                '70TB',
                '68TB',
                '105TB',
                '140TB',
                '132TB',
                '35TB',
                '21.6TB',
                '32TB',
                '280TB',
                '472TB',
                '760GB',
                '550GB',
                '1650GB',
                '2.0TB',
                '2.6TB',
                '5.2TB',
                '3.80TB',
                '1.61TB',
                '825GB',
                '1.86TB',
                '69GB',
                '1100GB',
                '1551GB',
                '1860GB',
                '1.25TB',
                '410GB',
                '2600GB',
                '249GB',
                '96GB',
                '1.44TB',
                '6.40TB',
                '12.8TB',
                '7.6TB',
                '7.86GB',
                '3.20TB',
                '30.72TB',
                '7.86TB',
                '7.84TB',
                '25.6TB',
                '7.7TB',
            ],
            'interface' => [
                '1.Gb/s SATA',
                'PCIe',
                'mSATA',
                'NVMe',
                'USB',
            ],
            'cache' => [
                '8MB',
                '32MB',
                '16MB',
                '2MB',
                '128MB',
                '64MB',
                '256MB',
                '4MB',
                '160KB',
                '512MB',
            ],
            'form_factor' => [
                'Low Profile',
                'Mezzanine',
                'Full Height',
                'ATX',
                'BTX',
                'Micro ATX',
                'Mini ITX',
                'Micro BTX',
                'EATX',
                'Pico BTX',
                'Half Height',
                'OCP3',
                'OCP',
                'SFF',
                'SFX',
                'Rack-Mountable',
                'Desktop',
                'Wall-Mountable',
                'Handheld',
                'Presentation',
                'Fixed',
                'In Counter',
                'Wearable',
                'Portable',
                'Rack Mountable',
                'External',
                'Internal',
                'GBIC',
                'SFP',
                'SFP Plus',
                'XFP',
                'X2',
                'Xenpak',
                'QSFP Plus',
                'QSFP',
                'SFP28',
                'QSFP28',
            ],
        ];
    }
}
