<?php

declare(strict_types=1);

namespace BSD\ProductAttributes\Model\Config;

class StorageAttributeOptions
{
    public static function getDefinitions(): array
    {
        return [
            'capacity' => [
                'label' => 'Capacity',
                'options' => [
                '250GB',
                '1TB',
                '6TB',
                '2TB',
                '146GB',
                '4TB',
                '8TB',
                '600GB',
                '160GB',
                '500GB',
                '120GB',
                '147GB',
                '300GB',
                '320GB',
                '200GB',
                '750GB',
                '150GB',
                '400GB',
                '640GB',
                '3TB',
                '900GB',
                '5TB',
                '1.2TB',
                '1.8TB',
                '10TB',
                '450GB',
                '181.6GB',
                '12TB',
                '146.8GB',
                '2000GB',
                '1.5TB',
                '123.5GB',
                '144GB',
                '180GB',
                '185.2GB',
                '147.1GB',
                '146.3GB',
                '360GB',
                '96TB',
                '16TB',
                '888GB',
                '181GB',
                '800GB',
                '139GB',
                '283.7GB',
                '141GB',
                '428GB',
                '146.4GB',
                '283GB',
                '1.3TB',
                '2.4TB',
                '181.60GB',
                '147.10GB',
                '146.90GB',
                '146.80GB',
                '1.6TB',
                '350GB',
                '14TB',
                '325GB',
                '147.8GB',
                '240GB',
                '2.5TB',
                '1.75TB',
                '7TB',
                '7.2TB',
                '3.6TB',
                '4.8TB',
                '146.30GB',
                '1.50TB',
                '145GB',
                '204GB',
                '256GB',
                '128GB',
                '1.1TB',
                '1.4TB',
                '571GB',
                '1.7TB',
                '1.14TB',
                '282.25GB',
                '127GB',
                '139.5GB',
                '141.12GB',
                '401GB',
                '282GB',
                '181.5GB',
                '857GB',
                '30TB',
                '140GB',
                '220GB',
                '650GB',
                '4.5TB',
                '4.9TB',
                '5.9TB',
                '6.2TB',
                '6.3TB',
                '6.4TB',
                '808.8GB',
                '216GB',
                '145.6GB',
                '960GB',
                '18TB',
                '20TB',
                '22TB',
                '1000GB',
                '12000GB',
                '16000GB',
                '4000GB',
                '24TB',
                '28TB',
                '26TB'
                ],
            ],
            'rpm' => [
                'label' => 'RPM',
                'options' => [
                '5400RPM',
                '7200RPM',
                '10000RPM',
                '15000RPM',
                '4200RPM',
                '5900RPM',
                '5700RPM',
                '3600RPM',
                '5760RPM',
                '4260RPM',
                '5600RPM',
                '5940RPM',
                '5200RPM',
                '7400RPM'
                ],
            ],
            'interface' => [
                'label' => 'Interface',
                'options' => [
                '1.5Gb/s SATA',
                '6Gb/s SATA',
                '3Gb/s SATA',
                'SATA',
                '12Gb/s SAS',
                '2Gb/s Fibre Channel',
                '6Gb/s SAS',
                'IDE ATA/100',
                'Ultra-320 SCSI',
                'IDE',
                'SAS',
                'Fibre Channel',
                '3Gb/s SAS',
                '4Gb/s Fibre Channel',
                '6Gb/s Fibre Channel',
                '3Gb/s Fibre Channel',
                '4Gb/s SATA',
                '1.5Gb/s Fibre Channel',
                '24Gb/s Fibre Channel',
                'SCSI',
                'IDE ATA/133',
                'Ultra-160 SCSI',
                'IDE ATA/66',
                '12Gb/s SATA',
                '2Gb/s SAS',
                '4Gb/s SAS',
                'Ultra SCSI'
                ],
            ],
            'cache' => [
                'label' => 'Cache',
                'options' => [
                '8MB Cache',
                '32MB Cache',
                '16MB Cache',
                '2MB Cache',
                '128MB Cache',
                '64MB Cache',
                '256MB Cache',
                '4MB Cache',
                '160KB Cache',
                '512MB Cache'
                ],
            ],
            'form_factor' => [
                'label' => 'Form Factor',
                'options' => [
                '2.5-inch',
                '3.5-inch',
                '1.8-inch',
                '5.25-inch'
                ],
            ],
            'storage_product_type' => [
                'label' => 'Product type',
                'options' => [
                'Hard Drive',
                'Internal Hard Drive',
                'External Hard Drive'
                ],
            ],
        ];
    }

    public static function getAttributeCodes(): array
    {
        return array_keys(self::getDefinitions());
    }
}

