<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentCategory;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Framework\Escaper;

/** @var ListProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var CurrentCategory $currentCategoryViewModel */

$currentCategoryViewModel = $viewModels->require(CurrentCategory::class);

$eagerLoadImagesCount = (int) ($block->getData('eager_load_images_count') ?? 3);
$productCollection = $block->getLoadedProductCollection();
$cardBlock = $block->getChildBlock('product.card');

?>
<?php if (!$productCollection->count()): ?>
    <div class="message info empty">
        <div>
            <?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?>
        </div>
    </div>
<?php elseif ($cardBlock): ?>
    <section class="py-8" id="product-list" aria-label="<?= $escaper->escapeHtmlAttr(__('Product list')) ?>" tabindex="-1">
        <?= $block->getToolbarHtml() ?>
        <?= $block->getAdditionalHtml() ?>
        <div class="products wrapper mode-grid products-grid">
            <ul
                role="list"
                class="mx-auto pt-4 pb-12 grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3"
            >
                <?php
                /** @var \Magento\Catalog\Model\Product $product */
                foreach (array_values($productCollection->getItems()) as $i => $product):
                    if ($i < $eagerLoadImagesCount) {
                        $product->setData('image_custom_attributes', ['loading' => 'eager', 'fetchpriority' => 'high']);
                    } else {
                        $product->unsetData('image_custom_attributes');
                    }
                    ?>
                    <li class="flex flex-col h-full">
                        <?= $cardBlock->setData('product', $product)->toHtml() ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    </section>
<?php endif; ?>
