<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */
?>

<div class="bb-pdp-page">
    <div class="bb-pdp-page__layout">
        <div class="bb-pdp-page__main">
            <section
                class="bb-pdp-hero pb-6 md:py-6 grid grid-cols-1 gap-4 md:items-start md:grid-cols-[34%_minmax(0px,1fr)] lg:grid-cols-[32%_minmax(0px,1fr)] lg:gap-x-10"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Product Info')) ?>"
            >
                <?= $block->getChildHtml('product.media') ?>
                <?= $block->getChildHtml('product.info') ?>
            </section>

            <?= $block->getChildHtml('product_options_wrapper_bottom') ?>

            <div class="bb-pdp-page__details">
                <?= $block->getChildHtml('product.info.details'); ?>
            </div>
        </div>

        <?= $block->getChildHtml('product.detail.sidebar') ?>
    </div>
</div>
